export const SUCCESS = "SUCCESS"
export const ERROR = "ERROR"
const ROLE_VAN_THU_TRUONG = "9997"
const ROLE_TRUONG_PHONG_HANH_CHINH = "9998"

export const CONSTANTS = {
    SUCCESS, ERROR, ROLE_VAN_THU_TRUONG, ROLE_TRUONG_PHONG_HANH_CHINH
}